package au.csiro.feedback.model;

// Generated 24/10/2015 11:50:16 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * FeedbackitemSupplementary generated by hbm2java
 */
@Entity
@Table(name = "feedbackitem_supplementary", catalog = "userfeedback")
public class FeedbackitemSupplementary implements java.io.Serializable {

	private Integer objectId;
	private FeedbackItem feedbackItem;
	private SupplementaryFiles supplementaryFiles;

	public FeedbackitemSupplementary() {
	}

	public FeedbackitemSupplementary(FeedbackItem feedbackItem, SupplementaryFiles supplementaryFiles) {
		this.feedbackItem = feedbackItem;
		this.supplementaryFiles = supplementaryFiles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "object_id", unique = true, nullable = false)
	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	@Cascade({CascadeType.ALL})
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "feedbackitem_id", nullable = false)
	public FeedbackItem getFeedbackItem() {
		return this.feedbackItem;
	}

	public void setFeedbackItem(FeedbackItem feedbackItem) {
		this.feedbackItem = feedbackItem;
	}

	@Cascade({CascadeType.ALL})
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "supplementfile_id", nullable = false)
	public SupplementaryFiles getSupplementaryFiles() {
		return this.supplementaryFiles;
	}

	public void setSupplementaryFiles(SupplementaryFiles supplementaryFiles) {
		this.supplementaryFiles = supplementaryFiles;
	}

}
