package au.csiro.feedback.model;

// Generated 24/10/2015 11:50:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FeedbackUser generated by hbm2java
 */
@Entity
@Table(name = "feedback_user", catalog = "userfeedback")
public class FeedbackUser implements java.io.Serializable {

	private Integer userId;
	private Date dateFirstFeedback;
	private Date dateLatestFeedback;
	private Integer totalFeedback;
	private String name;
	private String email;
	private String organization;
	private String username;
	private String password;
	private String expertiseLevel;
	private Boolean ispublic;
	private Set<FeedbackItem> feedbackItems = new HashSet<FeedbackItem>(0);

	public FeedbackUser() {
	}

	public FeedbackUser(Date dateFirstFeedback, Date dateLatestFeedback, Integer totalFeedback, String name,
			String email, String organization, String username, String password, String expertiseLevel,
			Boolean ispublic, Set<FeedbackItem> feedbackItems) {
		this.dateFirstFeedback = dateFirstFeedback;
		this.dateLatestFeedback = dateLatestFeedback;
		this.totalFeedback = totalFeedback;
		this.name = name;
		this.email = email;
		this.organization = organization;
		this.username = username;
		this.password = password;
		this.expertiseLevel = expertiseLevel;
		this.ispublic = ispublic;
		this.feedbackItems = feedbackItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_first_feedback", length = 19)
	public Date getDateFirstFeedback() {
		return this.dateFirstFeedback;
	}

	public void setDateFirstFeedback(Date dateFirstFeedback) {
		this.dateFirstFeedback = dateFirstFeedback;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_latest_feedback", length = 19)
	public Date getDateLatestFeedback() {
		return this.dateLatestFeedback;
	}

	public void setDateLatestFeedback(Date dateLatestFeedback) {
		this.dateLatestFeedback = dateLatestFeedback;
	}

	@Column(name = "total_feedback")
	public Integer getTotalFeedback() {
		return this.totalFeedback;
	}

	public void setTotalFeedback(Integer totalFeedback) {
		this.totalFeedback = totalFeedback;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "organization", length = 45)
	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "expertise_level", length = 45)
	public String getExpertiseLevel() {
		return this.expertiseLevel;
	}

	public void setExpertiseLevel(String expertiseLevel) {
		this.expertiseLevel = expertiseLevel;
	}

	@Column(name = "ispublic")
	public Boolean getIspublic() {
		return this.ispublic;
	}

	public void setIspublic(Boolean ispublic) {
		this.ispublic = ispublic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedbackUser")
	public Set<FeedbackItem> getFeedbackItems() {
		return this.feedbackItems;
	}

	public void setFeedbackItems(Set<FeedbackItem> feedbackItems) {
		this.feedbackItems = feedbackItems;
	}

}
