package au.csiro.feedback.model;

// Generated 24/10/2015 11:50:16 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * FeedbackcollectionTarget generated by hbm2java
 */
@Entity
@Table(name = "feedbackcollection_target", catalog = "userfeedback")
public class FeedbackcollectionTarget implements java.io.Serializable {

	private Integer objectId;
	private FeedbackTarget feedbackTarget;
	private FeedbackCollection feedbackCollection;

	public FeedbackcollectionTarget() {
	}

	public FeedbackcollectionTarget(FeedbackTarget feedbackTarget, FeedbackCollection feedbackCollection) {
		this.feedbackTarget = feedbackTarget;
		this.feedbackCollection = feedbackCollection;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "object_id", unique = true, nullable = false)
	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}
	
	@Cascade({CascadeType.ALL})
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "target_id", nullable = false)
	public FeedbackTarget getFeedbackTarget() {
		return this.feedbackTarget;
	}

	public void setFeedbackTarget(FeedbackTarget feedbackTarget) {
		this.feedbackTarget = feedbackTarget;
	}

	@Cascade({CascadeType.ALL})
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feedback_collection_id", nullable = false)
	public FeedbackCollection getFeedbackCollection() {
		return this.feedbackCollection;
	}

	public void setFeedbackCollection(FeedbackCollection feedbackCollection) {
		this.feedbackCollection = feedbackCollection;
	}

}
