package au.csiro.feedback.model;

// Generated 24/10/2015 11:50:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FeedbackTypes generated by hbm2java
 */
@Entity
@Table(name = "feedback_types", catalog = "userfeedback")
public class FeedbackTypes implements java.io.Serializable {

	private Integer feedbacktypeId;
	private String feedbacktypeCode;
	private String feedbacktypeDesc;
	private String identifier;
	private Set<FeedbackItem> feedbackItems = new HashSet<FeedbackItem>(0);

	public FeedbackTypes() {
	}

	public FeedbackTypes(String feedbacktypeCode) {
		this.feedbacktypeCode = feedbacktypeCode;
	}

	public FeedbackTypes(String feedbacktypeCode, String feedbacktypeDesc, String identifier,
			Set<FeedbackItem> feedbackItems) {
		this.feedbacktypeCode = feedbacktypeCode;
		this.feedbacktypeDesc = feedbacktypeDesc;
		this.identifier = identifier;
		this.feedbackItems = feedbackItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "feedbacktype__id", unique = true, nullable = false)
	public Integer getFeedbacktypeId() {
		return this.feedbacktypeId;
	}

	public void setFeedbacktypeId(Integer feedbacktypeId) {
		this.feedbacktypeId = feedbacktypeId;
	}

	@Column(name = "feedbacktype_code", nullable = false, length = 50)
	public String getFeedbacktypeCode() {
		return this.feedbacktypeCode;
	}

	public void setFeedbacktypeCode(String feedbacktypeCode) {
		this.feedbacktypeCode = feedbacktypeCode;
	}

	@Column(name = "feedbacktype_desc", length = 100)
	public String getFeedbacktypeDesc() {
		return this.feedbacktypeDesc;
	}

	public void setFeedbacktypeDesc(String feedbacktypeDesc) {
		this.feedbacktypeDesc = feedbacktypeDesc;
	}

	@Column(name = "identifier", length = 250)
	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedbackTypes")
	public Set<FeedbackItem> getFeedbackItems() {
		return this.feedbackItems;
	}

	public void setFeedbackItems(Set<FeedbackItem> feedbackItems) {
		this.feedbackItems = feedbackItems;
	}

}
