package au.csiro.feedback.model;

// Generated 24/10/2015 11:50:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "userfeedback")
public class Status implements java.io.Serializable {

	private Integer statusId;
	private String code;
	private String description;
	private Set<FeedbackItem> feedbackItems = new HashSet<FeedbackItem>(0);

	public Status() {
	}

	public Status(String code) {
		this.code = code;
	}

	public Status(String code, String description, Set<FeedbackItem> feedbackItems) {
		this.code = code;
		this.description = description;
		this.feedbackItems = feedbackItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "status_id", unique = true, nullable = false)
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Column(name = "code", nullable = false, length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<FeedbackItem> getFeedbackItems() {
		return this.feedbackItems;
	}

	public void setFeedbackItems(Set<FeedbackItem> feedbackItems) {
		this.feedbackItems = feedbackItems;
	}

}
