package au.csiro.feedback.model;

// Generated 24/10/2015 11:50:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * SupplementaryFiles generated by hbm2java
 */
@Entity
@Table(name = "supplementary_files", catalog = "userfeedback")
public class SupplementaryFiles implements java.io.Serializable {

	private Integer fileId;
	private String fileName;
	private String fileExtension;
	private String filePath;
	private Long fileSize;
	private Date uploadTime;
	private byte[] file;
	private Set<FeedbackitemSupplementary> feedbackitemSupplementaries = new HashSet<FeedbackitemSupplementary>(0);

	public SupplementaryFiles() {
	}

	public SupplementaryFiles(String fileName, String fileExtension) {
		this.fileName = fileName;
		this.fileExtension = fileExtension;
	}

	public SupplementaryFiles(String fileName, String fileExtension, String filePath, Long fileSize, Date uploadTime,
			byte[] file, Set<FeedbackitemSupplementary> feedbackitemSupplementaries) {
		this.fileName = fileName;
		this.fileExtension = fileExtension;
		this.filePath = filePath;
		this.fileSize = fileSize;
		this.uploadTime = uploadTime;
		this.file = file;
		this.feedbackitemSupplementaries = feedbackitemSupplementaries;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "file_id", unique = true, nullable = false)
	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	@Column(name = "file_name", nullable = false, length = 50)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_extension", nullable = false, length = 20)
	public String getFileExtension() {
		return this.fileExtension;
	}

	public void setFileExtension(String fileExtension) {
		this.fileExtension = fileExtension;
	}

	@Column(name = "file_path", length = 100)
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Column(name = "file_size")
	public Long getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upload_time", length = 19)
	public Date getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	@Column(name = "file")
	public byte[] getFile() {
		return this.file;
	}

	public void setFile(byte[] file) {
		this.file = file;
	}

	@Cascade({CascadeType.ALL})
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "supplementaryFiles")
	public Set<FeedbackitemSupplementary> getFeedbackitemSupplementaries() {
		return this.feedbackitemSupplementaries;
	}

	public void setFeedbackitemSupplementaries(Set<FeedbackitemSupplementary> feedbackitemSupplementaries) {
		this.feedbackitemSupplementaries = feedbackitemSupplementaries;
	}

}
