package au.csiro.feedback.model;

// Generated 24/10/2015 11:50:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TargetType generated by hbm2java
 */
@Entity
@Table(name = "target_type", catalog = "userfeedback", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class TargetType implements java.io.Serializable {

	private Integer typeId;
	private String code;
	private String descriptions;
	private String url;
	private Set<FeedbackTarget> feedbackTargets = new HashSet<FeedbackTarget>(0);

	public TargetType() {
	}

	public TargetType(String code) {
		this.code = code;
	}

	public TargetType(String code, String descriptions, String url, Set<FeedbackTarget> feedbackTargets) {
		this.code = code;
		this.descriptions = descriptions;
		this.url = url;
		this.feedbackTargets = feedbackTargets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "type_id", unique = true, nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "code", unique = true, nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "descriptions", length = 100)
	public String getDescriptions() {
		return this.descriptions;
	}

	public void setDescriptions(String descriptions) {
		this.descriptions = descriptions;
	}

	@Column(name = "url", length = 50)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "targetType")
	public Set<FeedbackTarget> getFeedbackTargets() {
		return this.feedbackTargets;
	}

	public void setFeedbackTargets(Set<FeedbackTarget> feedbackTargets) {
		this.feedbackTargets = feedbackTargets;
	}

}
